/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

import java.beans.PropertyVetoException;

/**
 *
 * @author LAB7-PC7-USER
 */
public class FrmClasseCalendar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClasseCalendar
     */
    public FrmClasseCalendar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        lblCalendar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoriaCalendar = new javax.swing.JRadioButton();
        rbtEjemploCalendar = new javax.swing.JRadioButton();
        rbtPracticaCalendar = new javax.swing.JRadioButton();
        escritorio3 = new javax.swing.JDesktopPane();

        lblCalendar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCalendar.setText("CALENDAR");

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));

        buttonGroup2.add(rbtTeoriaCalendar);
        rbtTeoriaCalendar.setText("Teoria");
        rbtTeoriaCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaCalendarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtEjemploCalendar);
        rbtEjemploCalendar.setText("Ejemplo");
        rbtEjemploCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemploCalendarActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtPracticaCalendar);
        rbtPracticaCalendar.setText("Practica");
        rbtPracticaCalendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaCalendarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtPracticaCalendar)
                    .addComponent(rbtEjemploCalendar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtTeoriaCalendar, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(rbtTeoriaCalendar)
                .addGap(18, 18, 18)
                .addComponent(rbtEjemploCalendar)
                .addGap(18, 18, 18)
                .addComponent(rbtPracticaCalendar)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        escritorio3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout escritorio3Layout = new javax.swing.GroupLayout(escritorio3);
        escritorio3.setLayout(escritorio3Layout);
        escritorio3Layout.setHorizontalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );
        escritorio3Layout.setVerticalGroup(
            escritorio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(escritorio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(lblCalendar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCalendar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritorio3))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaCalendarActionPerformed
        escritorio3.removeAll();
        escritorio3.repaint();
        FrmiTeoriaCalendar frmiTeoriaCalendar = new FrmiTeoriaCalendar();
        escritorio3.add(frmiTeoriaCalendar);
        frmiTeoriaCalendar.setVisible(true);
        try {
            frmiTeoriaCalendar.setMaximum(true);
            frmiTeoriaCalendar.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtTeoriaCalendarActionPerformed

    private void rbtEjemploCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemploCalendarActionPerformed
        escritorio3.removeAll();
        escritorio3.repaint();
        FrmiEjemploCalendar frmiEjemploCalendar = new FrmiEjemploCalendar();
        escritorio3.add(frmiEjemploCalendar);
        frmiEjemploCalendar.setVisible(true);
        try {
            frmiEjemploCalendar.setMaximum(true);
            frmiEjemploCalendar.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtEjemploCalendarActionPerformed

    private void rbtPracticaCalendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaCalendarActionPerformed
        escritorio3.removeAll();
        escritorio3.repaint();
        FrmiPracticaCalendar frmiPracticaCalendar = new FrmiPracticaCalendar();
        escritorio3.add(frmiPracticaCalendar);
        frmiPracticaCalendar.setVisible(true);
        try {
            frmiPracticaCalendar.setMaximum(true);
            frmiPracticaCalendar.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtPracticaCalendarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JDesktopPane escritorio3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalendar;
    private javax.swing.JRadioButton rbtEjemploCalendar;
    private javax.swing.JRadioButton rbtPracticaCalendar;
    private javax.swing.JRadioButton rbtTeoriaCalendar;
    // End of variables declaration//GEN-END:variables
}
