/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

import java.beans.PropertyVetoException;

/**
 *
 * @author LAB7-PC7-USER
 */
public class FrmClaseTime extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClaseTime
     */
    public FrmClaseTime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoriaTime = new javax.swing.JRadioButton();
        rbtEjemploTime = new javax.swing.JRadioButton();
        rbtPracticaTime = new javax.swing.JRadioButton();
        escritorio4 = new javax.swing.JDesktopPane();

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setText("TIME");

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        buttonGroup1.add(rbtTeoriaTime);
        rbtTeoriaTime.setText("Teoria");
        rbtTeoriaTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaTimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtEjemploTime);
        rbtEjemploTime.setText("Ejemplo");
        rbtEjemploTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemploTimeActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtPracticaTime);
        rbtPracticaTime.setText("Practica");
        rbtPracticaTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticaTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbtPracticaTime)
                    .addComponent(rbtEjemploTime)
                    .addComponent(rbtTeoriaTime, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(rbtTeoriaTime)
                .addGap(32, 32, 32)
                .addComponent(rbtEjemploTime)
                .addGap(31, 31, 31)
                .addComponent(rbtPracticaTime)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        escritorio4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout escritorio4Layout = new javax.swing.GroupLayout(escritorio4);
        escritorio4.setLayout(escritorio4Layout);
        escritorio4Layout.setHorizontalGroup(
            escritorio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorio4Layout.setVerticalGroup(
            escritorio4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(escritorio4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(lblTime)
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritorio4))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaTimeActionPerformed
        escritorio4.removeAll();
        escritorio4.repaint();
        FrmiTeoriaTime frmiTeoriaTime = new FrmiTeoriaTime();
        escritorio4.add(frmiTeoriaTime);
        frmiTeoriaTime.setVisible(true);
        try {
            frmiTeoriaTime.setMaximum(true);
            frmiTeoriaTime.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtTeoriaTimeActionPerformed

    private void rbtEjemploTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemploTimeActionPerformed
        escritorio4.removeAll();
        escritorio4.repaint();
        FrmiEjemploTime frmiEjemploTime = new FrmiEjemploTime();
        escritorio4.add(frmiEjemploTime);
        frmiEjemploTime.setVisible(true);
        try {
            frmiEjemploTime.setMaximum(true);
            frmiEjemploTime.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtEjemploTimeActionPerformed

    private void rbtPracticaTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticaTimeActionPerformed
        escritorio4.removeAll();
        escritorio4.repaint();
        FrmiPracticaTime frmiPracticaTime = new FrmiPracticaTime();
        escritorio4.add(frmiPracticaTime);
        frmiPracticaTime.setVisible(true);
        try {
            frmiPracticaTime.setMaximum(true);
            frmiPracticaTime.setMaximizable(true);
        } catch (PropertyVetoException e) {

        }
    }//GEN-LAST:event_rbtPracticaTimeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDesktopPane escritorio4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JRadioButton rbtEjemploTime;
    private javax.swing.JRadioButton rbtPracticaTime;
    private javax.swing.JRadioButton rbtTeoriaTime;
    // End of variables declaration//GEN-END:variables
}
