/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

import java.beans.PropertyVetoException;

/**
 *
 * @author LAB7-PC7-USER
 */
public class FrmDateUtil1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmDateUtil
     */
    public FrmDateUtil1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtGrupo1 = new javax.swing.ButtonGroup();
        lblDateUtil = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbtTeoria = new javax.swing.JRadioButton();
        rbtEjemplos = new javax.swing.JRadioButton();
        rbtPracticas = new javax.swing.JRadioButton();
        escritorio2 = new javax.swing.JDesktopPane();

        lblDateUtil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDateUtil.setText("DATE.util");

        jPanel1.setBackground(new java.awt.Color(204, 153, 255));

        rbtGrupo1.add(rbtTeoria);
        rbtTeoria.setText("Teoria");
        rbtTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtTeoriaActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtEjemplos);
        rbtEjemplos.setText("Ejemplos");
        rbtEjemplos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtEjemplosActionPerformed(evt);
            }
        });

        rbtGrupo1.add(rbtPracticas);
        rbtPracticas.setText("Practica");
        rbtPracticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPracticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtPracticas)
                    .addComponent(rbtEjemplos)
                    .addComponent(rbtTeoria))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rbtTeoria)
                .addGap(27, 27, 27)
                .addComponent(rbtEjemplos)
                .addGap(28, 28, 28)
                .addComponent(rbtPracticas)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout escritorio2Layout = new javax.swing.GroupLayout(escritorio2);
        escritorio2.setLayout(escritorio2Layout);
        escritorio2Layout.setHorizontalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        escritorio2Layout.setVerticalGroup(
            escritorio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(escritorio2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblDateUtil)
                        .addGap(0, 322, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblDateUtil)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escritorio2))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtTeoriaActionPerformed
        escritorio2.removeAll();
        escritorio2.repaint();
        FrmiTeoria frmiTeoria = new FrmiTeoria();
        escritorio2.add(frmiTeoria);
        frmiTeoria.setVisible(true);
        try {
            frmiTeoria.setMaximum(true);
            frmiTeoria.setMaximizable(true);
        } catch (PropertyVetoException e) {

    }//GEN-LAST:event_rbtTeoriaActionPerformed
}
    private void rbtEjemplosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtEjemplosActionPerformed
       escritorio2.removeAll();
        escritorio2.repaint();
        FrmiEjemplos frmiEjemplos = new FrmiEjemplos();
        escritorio2.add(frmiEjemplos);
        frmiEjemplos.setVisible(true);
        try {
            frmiEjemplos.setMaximum(true);
            frmiEjemplos.setMaximizable(true);
        } catch (PropertyVetoException e) {

    }                                        // TODO add your handling code here:
    }//GEN-LAST:event_rbtEjemplosActionPerformed

    private void rbtPracticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPracticasActionPerformed
         escritorio2.removeAll();
        escritorio2.repaint();
        FrmiPractica frmiPractica = new FrmiPractica();
        escritorio2.add(frmiPractica);
        frmiPractica.setVisible(true);
        try {
            frmiPractica.setMaximum(true);
            frmiPractica.setMaximizable(true);
        } catch (PropertyVetoException e) {

    }   
    }//GEN-LAST:event_rbtPracticasActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDateUtil;
    private javax.swing.JRadioButton rbtEjemplos;
    private javax.swing.ButtonGroup rbtGrupo1;
    private javax.swing.JRadioButton rbtPracticas;
    private javax.swing.JRadioButton rbtTeoria;
    // End of variables declaration//GEN-END:variables
}
