/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ister.vista.formularios;

/**
 *
 * @author LAB7-PC7-USER
 */
public class FrmiTeoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiTeoria
     */
    public FrmiTeoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtTeoria = new javax.swing.JTextArea();

        txtTeoria.setColumns(20);
        txtTeoria.setRows(5);
        txtTeoria.setText("TEORIA:\n                   CLASE DATE\nLa clase.Date representa un instante especifico\nen el tiempo con precision de mili segundos esta\nclase se encuentra dentro del package java.Util\ny es una de las clases mas utilizadas para el \ntrabajo con fechas\n");
        jScrollPane1.setViewportView(txtTeoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtTeoria;
    // End of variables declaration//GEN-END:variables
}
